Repository LSSTDESC/augur, pull requests merged in 2024-07, with the labels that each got.

#46 fixed inconsistency in the readme
  README.md
  environment.yml
Labels: bug, documentation

#47 draws more than 1 confidence interval
  augur/postprocess.py
  examples/config_test.yml
Labels: enhancement

#49 Issues/48 - Redshift distributions from file
  augur/analyze.py
  augur/generate.py
  augur/tracers/two_point.py
  data/srd_lens_bins_y1.txt
  data/srd_lens_bins_y10.txt
  data/srd_lens_bins_year_1.npy
  data/srd_lens_bins_year_10.npy
  data/srd_source_bins_y1.txt
  data/srd_source_bins_y10.txt
  data/srd_source_bins_year_1.npy
  data/srd_source_bins_year_10.npy
  examples/config_test.yml
Labels: enhancement

#53 Removed parameter hardcoding from CCL cosmology initialization
  augur/generate.py
Labels: enhancement

#57 Fix srd nz for the sources
  augur/tracers/two_point.py
Labels: bug

#64 Adding downstream accuracy CCL params
  augur/analyze.py
  augur/generate.py
  examples/config_test.yml
Labels: enhancement
